-- Вставка данных в таблицу Курьеры
INSERT INTO Couriers VALUES (1, 'Olga Kozlova', 89987654321, TO_DATE('2023-09-01', 'YYYY-MM-DD'),NULL); 
INSERT INTO Couriers VALUES (2, 'Sofia Ivanova', 89678901234, TO_DATE('2023-09-15', 'YYYY-MM-DD'),NULL); 
INSERT INTO Couriers VALUES (3, 'Anton Petrov', 89876543210, TO_DATE('2023-10-01', 'YYYY-MM-DD'),NULL); 
INSERT INTO Couriers VALUES (4, 'Elena Sidorova', 89012345678, TO_DATE('2023-10-31', 'YYYY-MM-DD'),NULL); 
INSERT INTO Couriers VALUES (5, 'Dmitry Smirnov', 89761234567, TO_DATE('2023-10-15', 'YYYY-MM-DD'),NULL); 
INSERT INTO Couriers VALUES (6, 'Anna Kuznetsova', 89654321098, TO_DATE('2023-11-01', 'YYYY-MM-DD'),NULL); 
INSERT INTO Couriers VALUES (7, 'Igor Volkov', 89321098765, TO_DATE('2023-11-15', 'YYYY-MM-DD'),NULL); 
INSERT INTO Couriers VALUES (8, 'Maria Fedorova', 89098765432, TO_DATE('2023-11-20', 'YYYY-MM-DD'),NULL); 
INSERT INTO Couriers VALUES (9, 'Alexei Ivanov', 89432109876, TO_DATE('2023-11-25', 'YYYY-MM-DD'),NULL); 
INSERT INTO Couriers VALUES (10, 'Botkov Dima', 89005469846, TO_DATE('2023-11-29', 'YYYY-MM-DD'),NULL); 

-- Вставка данных в таблицу Клиенты
INSERT INTO Clients VALUES (1, 'Vladimir Zaitsev', 89876543219);
INSERT INTO Clients VALUES (2, 'Ekaterina Morozova', 89456789012);
INSERT INTO Clients VALUES (3, 'Andrey Lebedev', 89019876543);
INSERT INTO Clients VALUES (4, 'Natalia Ivanova', 89765432109);
INSERT INTO Clients VALUES (5, 'Ivan Petrov', 89654321098);
INSERT INTO Clients VALUES (6, 'Yulia Sokolova', 89123456789);
INSERT INTO Clients VALUES (7, 'Sergei Popov', 89901234567);
INSERT INTO Clients VALUES (8, 'Alina Sidorova', 89432109876);
INSERT INTO Clients VALUES (9, 'Maxim Egorov', 89098765432);
INSERT INTO Clients VALUES (10, 'Polina Kiseleva', 89876543210);
INSERT INTO Clients VALUES (11, 'Alexei Ivanov', 89761234567);
INSERT INTO Clients VALUES (12, 'Anna Smirnova', 89654321098);
INSERT INTO Clients VALUES (13, 'Dmitry Kozlov', 89012345678);
INSERT INTO Clients VALUES (14, 'Olga Fedorova', 89987654321);
INSERT INTO Clients VALUES (15, 'Igor Volkov', 89321098765);
INSERT INTO Clients VALUES (16, 'Maria Petrova', 89214454299);
INSERT INTO Clients VALUES (17, 'Sofia Ivanova', 89678901234);
INSERT INTO Clients VALUES (18, 'Anton Semyonov', 89876543210);
INSERT INTO Clients VALUES (19, 'Elena Kuznetsova', 89098765432);
INSERT INTO Clients VALUES (20, 'Kirill Novikov', 89214454299);

-- Вставка данных в таблицу Пиццы
INSERT INTO Pizzas VALUES (1, 'Elemental Fusion Feast', 1899, 'Embark on a culinary journey with our Elemental Fusion Feast pizza, where the flavors of Mondstadt and Liyue converge. Savor the spicy warmth of Pyro-infused pepperoni, the refreshing burst of Anemo-inspired basil, and the earthy richness of Geo-infused truffle oil. Each bite is a harmonious blend of elemental delights, reminiscent of the diverse landscapes of Teyvat.');
INSERT INTO Pizzas VALUES (2, 'Abyssal Delight Supreme', 1299, 'Dive into the depths of flavor with our Abyssal Delight Supreme pizza. Immerse your taste buds in the mysterious depths of the ocean with succulent Abyssal Crabmeat, paired with Hydro-infused cucumber slices and the zesty kick of Electro-marinated calamari. This pizza promises a taste of the unknown, just like exploring the depths of the Abyss.');
INSERT INTO Pizzas VALUES (3, 'Celestial Stardust Surprise', 1099, 'Indulge in the ethereal magic of our Celestial Stardust Surprise pizza. Unearth the delicate flavors of Stardust Mushroom, paired with the enchanting sweetness of Anemo-infused honey glaze. Topped with radiant Celestial Pearls (edible, of course), every slice is a celestial dance on your palate, mirroring the cosmic wonders of Teyvat.');
INSERT INTO Pizzas VALUES (4, 'Dragonspine Blizzard Bliss', 999, 'Brace yourself for a chilling adventure with our Dragonspine Blizzard Bliss pizza. Feel the icy embrace of Cryo-kissed prosciutto and the crisp bite of fresh mint leaves, resembling the frozen landscape of Dragonspine. This pizza promises a cool, invigorating experience that echoes the majestic beauty of the frigid mountains.');
INSERT INTO Pizzas VALUES (5, 'Archons Bounty Banquet', 1099, 'Elevate your senses with the Archons Bounty Banquet pizza, a tribute to the divine delicacies of Teyvat. Revel in the luxurious taste of Ventis Windborne Basil, enriched with the decadence of Geo-infused truffle shavings and the celestial sweetness of Barbados Blueberry reduction. Each slice is a divine feast fit for an Archon.');
INSERT INTO Pizzas VALUES (6, 'Inazuma Thunderstrike Temptation', 699, 'Surrender to the electrifying allure of the Inazuma Thunderstrike Temptation pizza. Experience the shocking blend of Electro-spiced eel, paired with the intense heat of Pyro-infused red peppers and the invigorating freshness of Dendro-herbed goat cheese. This pizza promises a flavor explosion that mirrors the intensity of Inazumas thunderstorms.');
INSERT INTO Pizzas VALUES (7, 'Alchemists Elixir Extravaganza', 999, 'Immerse yourself in the alchemical wonders of the Alchemists Elixir Extravaganza pizza. Enjoy the unique fusion of Anemo-infused herbs, Electro-braised wild boar, and the subtle bitterness of Dendro-inspired artichoke hearts. Each bite is a mystical concoction that captures the essence of alchemical mastery in the culinary realm.');
INSERT INTO Pizzas VALUES (8, 'Vortex Visions Veggie Delight', 1099, 'Immerse yourself in the enchanting flavors of the Vortex Visions Veggie Delight pizza. Experience the swirling sensation of Anemo-infused spinach and kale, complemented by the vibrant hues of Hydro-infused cherry tomatoes and the earthy richness of Geo-roasted bell peppers. Every bite is a journey through a garden of elemental delights.');
INSERT INTO Pizzas VALUES (9, 'Mystic Moonlight Meat Lovers Masterpiece', 1299, 'Unleash your carnivorous cravings with the Mystic Moonlight Meat Lovers Masterpiece pizza. Revel in the succulence of Pyro-roasted lamb, the smoky depths of Dendro-infused wild boar sausage, and the hearty richness of Geo-cured bacon. This pizza promises a symphony of meaty flavors under the mystical glow of Teyvats moonlight.');
INSERT INTO Pizzas VALUES (10, 'Wandering Samurai Seafood Sensation', 1099, 'Embark on a culinary adventure with the Wandering Samurai Seafood Sensation pizza. Savor the delicate taste of Electro-marinated shrimp, paired with the umami explosion of Hydro-soaked seaweed and the fiery kick of Pyro-charred squid. This pizza captures the essence of the high seas and the spirit of a wandering samurai.');
INSERT INTO Pizzas VALUES (11, 'Starfall Symphony Sweet Treat', 1299, 'Indulge your sweet tooth with the Starfall Symphony Sweet Treat pizza. Delight in the heavenly combination of Celestial Pearls-infused mascarpone, Anemo-candied figs, and the luscious sweetness of Mondstadt apple compote. Each slice is a celestial symphony of flavors, promising a dessert experience that falls from the stars.');

-- Вставка данных в таблицу Адреса
INSERT INTO Addresses VALUES (1, 'Sunny Street, House 10, Apartment 3');
INSERT INTO Addresses VALUES (2, 'Spring Avenue, House 25, Apartment 7');
INSERT INTO Addresses VALUES (3, 'Azure Quay, House 18, Apartment 42');
INSERT INTO Addresses VALUES (4, 'Star Lane, House 5, Apartment 9');
INSERT INTO Addresses VALUES (5, 'Chocolate Drive, House 3, Apartment 21');
INSERT INTO Addresses VALUES (6, 'Friendship Street, House 7, Apartment 15');
INSERT INTO Addresses VALUES (7, 'Fragrance Square, House 12, Apartment 30');
INSERT INTO Addresses VALUES (8, 'Forgotten Alley, House 2, Apartment 8');
INSERT INTO Addresses VALUES (9, 'Joke Boulevard, House 14, Apartment 6');
INSERT INTO Addresses VALUES (10, 'Melody Street, House 31, Apartment 12');
INSERT INTO Addresses VALUES (11, 'Power Boulevard, House 9, Apartment 5');
INSERT INTO Addresses VALUES (12, 'Mysterious Dead End, House 6, Apartment 24');
INSERT INTO Addresses VALUES (13, 'Fairy Lane, House 17, Apartment 11');
INSERT INTO Addresses VALUES (14, 'Hypnotic Street, House 23, Apartment 4');
INSERT INTO Addresses VALUES (15, 'Virtual Square, House 8, Apartment 16');
INSERT INTO Addresses VALUES (16, 'Rainbow Drive, House 13, Apartment 33');
INSERT INTO Addresses VALUES (17, 'Fantastic Quay, House 20, Apartment 14');
INSERT INTO Addresses VALUES (18, 'Hidden Street, House 11, Apartment 22');
INSERT INTO Addresses VALUES (19, 'Marvelous Alley, House 4, Apartment 27');
INSERT INTO Addresses VALUES (20, 'Pink Boulevard, House 19, Apartment 10');

-- Вставка данных в таблицу Заказы
INSERT INTO Orders VALUES (1, 5, 1, 7, 'Home', 'Love pizza with pineapple!');
INSERT INTO Orders VALUES (2, 8, 3, 18, 'Office', 'Please add extra cheese.');
INSERT INTO Orders VALUES (3, 2, 12, 5, NULL, NULL);
INSERT INTO Orders VALUES (4, 7, 19, 4, 'Home', NULL);
INSERT INTO Orders VALUES (5, 3, 8, 14, NULL, 'Put a little ketchup separately.');
INSERT INTO Orders VALUES (6, 9, 11, 1, NULL, 'Make the pizza crust thick!');
INSERT INTO Orders VALUES (7, 4, 16, 10, 'Home', NULL);
INSERT INTO Orders VALUES (8, 6, 18, 20, NULL, 'Add a couple of lemonades, please.');
INSERT INTO Orders VALUES (9, 10, 20, 13, NULL, 'No mushrooms, please!');
INSERT INTO Orders VALUES (10, 1, 9, 2, NULL, NULL);
INSERT INTO Orders VALUES (11, 5, 14, 8, 'Home', 'Let the courier call in 10 minutes!');
INSERT INTO Orders VALUES (12, 8, 6, 17, NULL, 'Deliver with a gift menu!');
INSERT INTO Orders VALUES (13, 2, 10, 3, NULL, 'No onions, please!');
INSERT INTO Orders VALUES (14, 7, 15, 11, NULL, 'Thanks for the fast delivery!');
INSERT INTO Orders VALUES (15, 3, 4, 19, NULL, 'Make it with a thin crust!');
INSERT INTO Orders VALUES (16, 9, 2, 6, NULL, 'Add a couple of salt packets!');
INSERT INTO Orders VALUES (17, 4, 17, 9, 'Home', NULL);
INSERT INTO Orders VALUES (18, 6, 5, 16, NULL, 'Give me a double portion of ketchup!');
INSERT INTO Orders VALUES (19, 10, 13, 4, NULL, 'No tomatoes, please!');
INSERT INTO Orders VALUES (20, 1, 7, 18, NULL, NULL);
INSERT INTO Orders VALUES (21, 3, 18, 6, 'Office', NULL);
INSERT INTO Orders VALUES (22, 6, 9, 15, NULL, 'Extra crispy crust, please!');
INSERT INTO Orders VALUES (23, 1, 14, 11, 'Home', 'Half pepperoni, half mushrooms.');
INSERT INTO Orders VALUES (24, 8, 4, 20, NULL, 'Include some Parmesan packets!');
INSERT INTO Orders VALUES (25, 5, 7, 12, 'Office', NULL);
INSERT INTO Orders VALUES (26, 9, 16, 8, NULL, 'No olives, please!');
INSERT INTO Orders VALUES (27, 2, 11, 3, 'Home', NULL);
INSERT INTO Orders VALUES (28, 7, 8, 19, 'Office', 'Square-cut slices, if possible!');
INSERT INTO Orders VALUES (29, 4, 17, 13, NULL, NULL);
INSERT INTO Orders VALUES (30, 10, 6, 14, 'Home', 'Surprise me with the toppings!');
INSERT INTO Orders VALUES (31, 3, 12, 5, 'Office', NULL);
INSERT INTO Orders VALUES (32, 8, 19, 2, NULL, 'Extra garlic butter on the crust!');
INSERT INTO Orders VALUES (33, 2, 15, 9, NULL, NULL);
INSERT INTO Orders VALUES (34, 7, 10, 16, 'Home', 'Delivery instructions: Ring the doorbell twice.');
INSERT INTO Orders VALUES (35, 5, 13, 4, NULL, 'Light on the tomato sauce, please.');
INSERT INTO Orders VALUES (36, 9, 14, 7, 'Office', NULL);
INSERT INTO Orders VALUES (37, 4, 8, 18, NULL, 'Include some red pepper flakes!');
INSERT INTO Orders VALUES (38, 6, 20, 1, 'Home', 'No cheese, but extra veggies!');
INSERT INTO Orders VALUES (39, 10, 7, 17, NULL, NULL);
INSERT INTO Orders VALUES (40, 1, 16, 10, 'Office', 'Draw a smiley face on the box!');
INSERT INTO Orders VALUES (41, 3, 9, 13, NULL, 'Cut it into squares, please!');
INSERT INTO Orders VALUES (42, 8, 14, 6, 'Home', NULL);
INSERT INTO Orders VALUES (43, 2, 10, 18, NULL, 'Add a side of ranch dressing!');
INSERT INTO Orders VALUES (44, 7, 15, 5, 'Office', 'Leave it on the doorstep, I will tip in the app.');
INSERT INTO Orders VALUES (45, 5, 11, 2, NULL, 'No green peppers, please.');
INSERT INTO Orders VALUES (46, 9, 12, 19, 'Home', NULL);
INSERT INTO Orders VALUES (47, 4, 17, 8, NULL, 'Include a menu for next time!');
INSERT INTO Orders VALUES (48, 6, 13, 4, 'Office', 'Make it spicy!');
INSERT INTO Orders VALUES (49, 10, 8, 15, NULL, NULL);
INSERT INTO Orders VALUES (50, 1, 11, 7, 'Home', 'Dont forget the napkins!');

-- Вставка данных в таблицу Детали заказа
INSERT INTO OrderDetails VALUES (1, 1, 5, 2);
INSERT INTO OrderDetails VALUES (2, 2, 5, 3);
INSERT INTO OrderDetails VALUES (3, 2, 8, 1);
INSERT INTO OrderDetails VALUES (4, 3, 2, 2);
INSERT INTO OrderDetails VALUES (5, 4, 4, 1);
INSERT INTO OrderDetails VALUES (6, 5, 8, 3);
INSERT INTO OrderDetails VALUES (7, 5, 1, 1);
INSERT INTO OrderDetails VALUES (8, 6, 7, 3);
INSERT INTO OrderDetails VALUES (9, 7, 4, 2);
INSERT INTO OrderDetails VALUES (10, 8, 6, 1);
INSERT INTO OrderDetails VALUES (11, 8, 9, 3);
INSERT INTO OrderDetails VALUES (12, 9, 3, 2);
INSERT INTO OrderDetails VALUES (13, 9, 1, 1);
INSERT INTO OrderDetails VALUES (14, 9, 6, 3);
INSERT INTO OrderDetails VALUES (15, 9, 11, 1);
INSERT INTO OrderDetails VALUES (16, 10, 2, 2);
INSERT INTO OrderDetails VALUES (17, 11, 7, 3);
INSERT INTO OrderDetails VALUES (18, 12, 3, 2);
INSERT INTO OrderDetails VALUES (19, 13, 5, 1);
INSERT INTO OrderDetails VALUES (20, 14, 2, 3);
INSERT INTO OrderDetails VALUES (21, 14, 8, 2);
INSERT INTO OrderDetails VALUES (22, 15, 4, 3);
INSERT INTO OrderDetails VALUES (23, 15, 5, 1);
INSERT INTO OrderDetails VALUES (24, 15, 1, 2);
INSERT INTO OrderDetails VALUES (25, 16, 2, 1);
INSERT INTO OrderDetails VALUES (26, 16, 8, 3);
INSERT INTO OrderDetails VALUES (27, 16, 10, 1);
INSERT INTO OrderDetails VALUES (28, 17, 7, 3);
INSERT INTO OrderDetails VALUES (29, 17, 5, 2);
INSERT INTO OrderDetails VALUES (30, 18, 6, 1);
INSERT INTO OrderDetails VALUES (31, 19, 9, 3);
INSERT INTO OrderDetails VALUES (32, 19, 3, 2);
INSERT INTO OrderDetails VALUES (33, 19, 9, 1);
INSERT INTO OrderDetails VALUES (34, 20, 6, 3);
INSERT INTO OrderDetails VALUES (35, 20, 11, 1);
INSERT INTO OrderDetails VALUES (36, 21, 4, 2);
INSERT INTO OrderDetails VALUES (37, 21, 8, 1);
INSERT INTO OrderDetails VALUES (38, 22, 5, 3);
INSERT INTO OrderDetails VALUES (39, 22, 7, 2);
INSERT INTO OrderDetails VALUES (40, 23, 2, 1);
INSERT INTO OrderDetails VALUES (41, 24, 9, 3);
INSERT INTO OrderDetails VALUES (42, 24, 6, 2);
INSERT INTO OrderDetails VALUES (43, 25, 3, 1);
INSERT INTO OrderDetails VALUES (44, 26, 7, 3);
INSERT INTO OrderDetails VALUES (45, 26, 8, 1);
INSERT INTO OrderDetails VALUES (46, 27, 4, 2);
INSERT INTO OrderDetails VALUES (47, 28, 6, 3);
INSERT INTO OrderDetails VALUES (48, 29, 8, 1);
INSERT INTO OrderDetails VALUES (49, 30, 5, 2);
INSERT INTO OrderDetails VALUES (50, 30, 2, 3);
INSERT INTO OrderDetails VALUES (51, 30, 10, 2);
INSERT INTO OrderDetails VALUES (52, 30, 7, 3);
INSERT INTO OrderDetails VALUES (53, 30, 5, 1);
INSERT INTO OrderDetails VALUES (54, 30, 8, 3);
INSERT INTO OrderDetails VALUES (55, 30, 3, 2);
INSERT INTO OrderDetails VALUES (56, 30, 9, 1);
INSERT INTO OrderDetails VALUES (57, 30, 6, 3);
INSERT INTO OrderDetails VALUES (58, 30, 11, 1);
INSERT INTO OrderDetails VALUES (59, 30, 2, 2);
INSERT INTO OrderDetails VALUES (60, 31, 7, 3);
INSERT INTO OrderDetails VALUES (61, 31, 5, 1);
INSERT INTO OrderDetails VALUES (62, 31, 6, 2);
INSERT INTO OrderDetails VALUES (63, 31, 9, 3);
INSERT INTO OrderDetails VALUES (64, 31, 3, 2);
INSERT INTO OrderDetails VALUES (65, 32, 9, 1);
INSERT INTO OrderDetails VALUES (66, 33, 6, 3);
INSERT INTO OrderDetails VALUES (67, 33, 11, 1);
INSERT INTO OrderDetails VALUES (68, 33, 4, 2);
INSERT INTO OrderDetails VALUES (69, 34, 8, 1);
INSERT INTO OrderDetails VALUES (70, 34, 5, 3);
INSERT INTO OrderDetails VALUES (71, 34, 7, 2);
INSERT INTO OrderDetails VALUES (72, 34, 2, 1);
INSERT INTO OrderDetails VALUES (73, 35, 9, 3);
INSERT INTO OrderDetails VALUES (74, 35, 6, 2);
INSERT INTO OrderDetails VALUES (75, 35, 3, 1);
INSERT INTO OrderDetails VALUES (76, 35, 7, 3);
INSERT INTO OrderDetails VALUES (77, 36, 8, 1);
INSERT INTO OrderDetails VALUES (78, 36, 4, 2);
INSERT INTO OrderDetails VALUES (79, 37, 6, 3);
INSERT INTO OrderDetails VALUES (80, 37, 8, 1);
INSERT INTO OrderDetails VALUES (81, 37, 5, 2);
INSERT INTO OrderDetails VALUES (82, 37, 2, 3);
INSERT INTO OrderDetails VALUES (83, 38, 10, 2);
INSERT INTO OrderDetails VALUES (84, 38, 7, 3);
INSERT INTO OrderDetails VALUES (85, 38, 5, 1);
INSERT INTO OrderDetails VALUES (86, 38, 8, 3);
INSERT INTO OrderDetails VALUES (87, 39, 3, 2);
INSERT INTO OrderDetails VALUES (88, 39, 9, 1);
INSERT INTO OrderDetails VALUES (89, 39, 6, 3);
INSERT INTO OrderDetails VALUES (90, 39, 11, 1);
INSERT INTO OrderDetails VALUES (91, 40, 2, 2);
INSERT INTO OrderDetails VALUES (92, 40, 7, 3);
INSERT INTO OrderDetails VALUES (93, 40, 5, 1);
INSERT INTO OrderDetails VALUES (94, 41, 6, 2);
INSERT INTO OrderDetails VALUES (95, 41, 9, 3);
INSERT INTO OrderDetails VALUES (96, 41, 3, 2);
INSERT INTO OrderDetails VALUES (97, 42, 9, 1);
INSERT INTO OrderDetails VALUES (98, 42, 6, 3);
INSERT INTO OrderDetails VALUES (99, 42, 11, 1);
INSERT INTO OrderDetails VALUES (100, 43, 4, 2);
INSERT INTO OrderDetails VALUES (101, 43, 8, 1);
INSERT INTO OrderDetails VALUES (102, 44, 5, 3);
INSERT INTO OrderDetails VALUES (103, 44, 7, 2);
INSERT INTO OrderDetails VALUES (104, 44, 2, 1);
INSERT INTO OrderDetails VALUES (105, 45, 9, 3);
INSERT INTO OrderDetails VALUES (106, 46, 6, 2);
INSERT INTO OrderDetails VALUES (107, 47, 3, 1);
INSERT INTO OrderDetails VALUES (108, 48, 7, 3);
INSERT INTO OrderDetails VALUES (109, 49, 8, 1);
INSERT INTO OrderDetails VALUES (110, 50, 4, 2);

COMMIT;
